womens_url: 'http://www.tennis-data.co.uk/YEARw/YEAR.xls'
mens_url: 'http://www.tennis-data.co.uk/YEAR/YEAR.xls'

tennis_data_url: 'http://www.tennis-data.co.uk/YEARw/YEAR.xls'
tennis_data_year_const: 'YEAR'
tennis_data_start_year: 2007
tennis_data_end_year: 2020

date_col: 'Date'
winner_col: 'Winner'
winner_pts: 'WPts'
loser_col: 'Loser'
loser_pts: 'LPts'
drop_na_cols: ['WPts','LPts']
min_matches: 9
